// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvjfnfdE4KffeCV9AeoEmd1SfheXxzYXQ',
    appId: '1:338590767004:android:0adc4f4c9529b3ce539a59',
    messagingSenderId: '338590767004',
    projectId: 'transitai',
    databaseURL: 'https://transitai-default-rtdb.firebaseio.com',
    storageBucket: 'transitai.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADMlwDndHyO9cecHHECLEY-vk8JsuHPhU',
    appId: '1:338590767004:web:8823a9b4ec520ec3539a59',
    messagingSenderId: '338590767004',
    projectId: 'transitai',
    authDomain: 'transitai.firebaseapp.com',
    databaseURL: 'https://transitai-default-rtdb.firebaseio.com',
    storageBucket: 'transitai.firebasestorage.app',
    measurementId: 'G-5CSQLRH51M',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADMlwDndHyO9cecHHECLEY-vk8JsuHPhU',
    appId: '1:338590767004:web:2b9b8254e55a59d1539a59',
    messagingSenderId: '338590767004',
    projectId: 'transitai',
    authDomain: 'transitai.firebaseapp.com',
    databaseURL: 'https://transitai-default-rtdb.firebaseio.com',
    storageBucket: 'transitai.firebasestorage.app',
    measurementId: 'G-V4FPBBZ8LF',
  );

}